name: Testing

on: push

env:
  TERM: linux

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          [
            "esp8266",
            "esp32",
            "wemos_d1_mini",
            "esp32minikit",
            "m5stickc",
            "m5stickc_plus",
            "wroom_02",
            "nodemcu",
            "sonoff",
            "olimex",
            "esp-m",
            "sonoff_pow",
          ]
        device:
          [
            "input",
            "output",
            "analog",
            "bmp180",
            "bmp280",
            "dallas",
            "gyro6050",
            "gyro9250",
            "gesture_apds9960",
            "sgp30",
            "edge_counter",
            "dht",
            "ds18b20",
            "servo",
            "acoustic_distance",
            "laser_distance",
            "weight_sensor",
            "light_sensor_1",
            "light_sensor_2",
            "capacity_touch",
          ]
    name: Test ${{ matrix.board }} with ${{ matrix.device }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          tags: iotempower:latest
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test installation
        run: docker run --entrypoint "/bin/bash" --rm -v "$GITHUB_WORKSPACE:/iot/data/repo" iotempower:latest -c "iot x pytest -s -v iot/tests/test_installations.py"
      # - name: Test compilation
      #   run: docker run --rm iotempower:latest iot x pytest -s -v tests/test_compilation.py --boards ${{ matrix.board }} --devices ${{ matrix.device }}
