name: Testing

on: push

env:
  TERM: linux

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install iotempower
        run: |
          bash run x bin/iot_install --default
      - name: Run tests
        run: |
          iot x pytest -s -v test_compilation.py --boards=wemos_d1_mini,esp32 --devices=laser_distance